---
- name: Install Kerberos Client Packages
  apt:
    name:
      - krb5-user
      - libpam-krb5
      - libpam-ccreds
    state: present

- name: Deploy krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
