---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Common System Packages
  apt:
    name: "{{ sys_packages }}"
    state: present

- name: Ensure Timezone is set
  timezone:
    name: "{{ timezone }}"
